services:
  web:
    build:
      context: .
      target: production
    ports:
      - "8080:80"
    environment:
      - "PORT=80"
      - "OPENWA_API_URL=${OPENWA_API_URL}"
      - "OPENWA_API_KEY=${OPENWA_API_KEY}"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
